version: "3.1"
services:
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8888:8081"
    # links:
    #   - database:database  # my database container is called postgres, not db
    environment:
      DATABASE_URL: postgres://postgres:123asd@database:5432/pavement_dev?sslmode=disable
    # depends_on:
    #   - database
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123asd
      POSTGRES_DB: pavement_dev
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data